apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7 # Imagem do MySQL que você deseja usar
          env:
            - name: DB_TYPE
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: DB_DATABASE
              value: "DB_LANCHONETE"
            - name: MYSQL_ROOT_PASSWORD
              value: $(DB_PASSWORD)
            - name: MYSQL_DATABASE
              value: $(DB_DATABASE)
            - name:  MYSQL_USER
              value: $(DB_USERNAME)
            - name:   MYSQL_PASSWORD
              value: $(DB_PASSWORD)   
            - name:   DB_HOST
              value: "svc-mysql"
          ports:
            - containerPort: 3306  # Porta padrão do MySQL
          